services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - live-status-data:/var/live-status
    restart: unless-stopped

  live-checker:
    build:
      context: .
      dockerfile: Dockerfile.live-checker
    volumes:
      - live-status-data:/var/live-status
    restart: unless-stopped

volumes:
  live-status-data: